#! /usr/bin/env bash
#
set -e

exec /usr/bin/bwrap --dev-bind / / \
    --bind /opt/weixin/crap/uos-release /etc/os-release \
    --bind /opt/weixin/crap/uos-lsb /etc/lsb-release \
    --bind /opt/weixin/crap/usr/lib/license/ /usr/lib/license \
    --bind /opt/weixin/crap/var/ /var \
    /opt/weixin/weixin.sh "$@"
